//student grading system
let m=parseInt(prompt("Enter Your Marks : "))
if (m>=90 && m<=100)
    document.write(`<h1>Grade : A</h1>`)
else if (m<=89 && m>=80)
    document.write(`<h2>Grade : B</h2>`)
else if (m<=79 && m>=70)
    document.write(`<h2>Grade : C</h2>`)
else if (m<=69 && m>=60)
    document.write(`<h2>Grade : D</h2>`)
else if (m<=59 && m>=50)
    document.write(`<h2>Grade : E</h2>`)
else if (m<=49 && m>=0)
    document.write(`<h2>Grade : F</h2>`)
else (m)
    document.write(`<h1>Invalid Input</h1>`)
